### ISSUE TITLE
API for getting userid for given username

### ISSUE THREAD

**Issue by anuveyatsu** [datahq/auth#14]
Endpoint: `/auth/resolve?username=<username>`

## Acceptance criteria

* [x] I can get userid for given username

## Tasks

* [x] `resolve-username(username)`
    * [x] Query DB for username
    * [x]  Return user-id (if exists) or null (in case it doesn't)

**Comment by anuveyatsu** [comment]
FIXED in #15
