### ISSUE TITLE
API for getting user profile information

### ISSUE THREAD

**Issue by anuveyatsu** [datahq/auth#18]
In the frontend, we want to show user profile information such as `joined_date` (maybe some more in the future). To do so we need to query auth db so we need to have API for it: `/auth/get_profile?username=core`.

## Acceptance criteria

* [x] I can hit `/auth/get_profile?username=core` and get profile information about the user

## Tasks

* [x] add a blueprint in `auth/blueprints.py`
* [x] add `get_user_profile_by_username` method in controllers
* [x] reuse `get_user_by_username` method for querying db

**Comment by anuveyatsu** [comment]
FIXED in #19
