### ISSUE TITLE
[Marketing ]Support service for emails

### ISSUE THREAD

**Issue by zelima** [datahq/auth#26]
We need another service (module) for communicating with mailing service, like MailChimp. Besides just allowing `emails` service, to avoid changes in the core of Auth module, we need to create a new external module that will handle permissions and make API requests for populating mailing list. 

## Acceptance Criteria

* [ ] The least modification to auth module 
* [ ] we have a new API for `emails`
* [ ] new users are added to the mailing list on MailChimp

## Tasks

* [ ] Create `emails` module
  * [ ] ~~`get_permissions()` function~~
  * [ ] handler to make requests
* [ ] Update list of modified services (allowing emails to get permissions)
* [ ] Use `emails` API to update mailing lists on Mailchimp from Auth

## Analysis 

Create new module `datahub/emails` with very simple API right now

```
add_user(user_info):
    mailchimp_user = os.environ.get('MAILCHIMP_USER')
    mailchimp_pass = os.environ.get('MAILCHIMP_PASS')
    requests.post('https://....', user={mailchimp_user:mailchimp_pass}, data=user_info) 
```

Inf Auth

```
# in controllers

import emails

def _get_token_from_profile(provider, profile, private_key):
   ...
   user = create_or_get_user(userid, name, username, email, avatar_url)
   if user.get('new'):
       emails.add_user(user)
   ...

# in models

def create_or_get_user(provider_id, name, username, email, avatar_url):
    id_ = hash_email(email)
    user = get_user(id_)
    if user is None:
        document = {
            'id': id_,
            'provider_id': provider_id,
            'username': username,
            'name': name,
            'email': email,
            'avatar_url': avatar_url,
            'join_date': datetime.datetime.now()
        }
        save_user(document)
        document['new'] = True  # tell controllers it's new
        return document
    return user
```

**Comment by zelima** [comment]
FIXED
